### PR TITLE
RFC: enable OneWire over GPIO for Pi 3B

### PR DESCRIPTION
**Pull request by dme**
Thank you for gokrazy, which is fun.

I'd like to use some OneWire temperature sensors on a Pi 3B with gokrazy, but the mechanism supported on Raspberry Pi Linux kernels (a device tree overlay) does not seem immediately applicable. Instead, update the Pi 3B device tree directly and then enable the relevant kernel modules.

It's not obvious that this is really the best approach - it forces support for OneWire over GPIO onto all Pi 3B users and doesn't help owners of other Pi devices at all (though presumably patches for their device tree could also be made).

Also, it's not clear that merging the Raspberry Pi Linux kernel overlay into the device tree blob was done correctly.

This does, however, make it all work for me.

Hence, RFC.

### CODE REVIEW

**Comment by stapelberg** [comment]
Hey, thanks for your PR!

Just a quick note to say this is not forgotten, my schedule is just pretty busy these days.

> It's not obvious that this is really the best approach - it forces support for OneWire over GPIO onto all Pi 3B users and doesn't help owners of other Pi devices at all (though presumably patches for their device tree could also be made).

Is there any downside to enabling this support? Like, does your change make anything no longer possible that used to be possible?

> but the mechanism supported on Raspberry Pi Linux kernels (a device tree overlay) does not seem immediately applicable

I wonder if we could make device tree overlays work. This doesn’t necessarily have to block your change, but it would be good to understand whether overlays would be possible at all or not, longer-term. 

We need to be careful with adding more kernel patches, because each patch comes with a certain maintenance burden. I have seen this in the past with other device tree patches, they frequently need updates and conflict resolution.

**Comment by dme** [comment]
> Just a quick note to say this is not forgotten, my schedule is just pretty busy these days.

Understood, and likewise.

> > It's not obvious that this is really the best approach - it forces support for OneWire over GPIO onto all Pi 3B users and doesn't help owners of other Pi devices at all (though presumably patches for their device tree could also be made).
> 
> Is there any downside to enabling this support? Like, does your change make anything no longer possible that used to be possible?

If someone is using the relevant GPIO pins for something else, it seems that this could conflict.

> > but the mechanism supported on Raspberry Pi Linux kernels (a device tree overlay) does not seem immediately applicable
> 
> I wonder if we could make device tree overlays work. This doesn’t necessarily have to block your change, but it would be good to understand whether overlays would be possible at all or not, longer-term.

I will try to find an approach using overlays, as it seems to be the upstream approach.

> We need to be careful with adding more kernel patches, because each patch comes with a certain maintenance burden. I have seen this in the past with other device tree patches, they frequently need updates and conflict resolution.

Agreed.

**Review by stapelberg — CHANGES_REQUESTED** [review]
I can definitely merge the kernel configuration change itself.

For the device tree changes, I think we should focus on getting device tree overlays supported instead of adding extra patches. I outlined the (few) remaining steps at https://github.com/gokrazy/gokrazy/issues/216#issuecomment-1852651182

Do you want to split up the PR to get the kernel config change merged and out of the way?

**Comment by dme** [comment]
Firstly, I should say that I updated this because I wanted an updated version, rather than to prod you into looking at it again.

I keep meaning to look at periph.io to see if it would avoid the need for the kernel onewire implementation, but have not got around to it.

Given that there seem to be other uses for devicetree overlays, I will split the PR as suggested, and should be able to look at the suggestions in https://github.com/gokrazy/gokrazy/issues/216#issuecomment-1852651182.

**Comment by dme** [comment]
Submitted #552 for the kernel configuration changes. Off to look at devicetree support...

**Comment by stapelberg** [comment]
I’ll close this now-obsolete PR, then.

Note that a bunch of steps have already happened towards device tree overlay support. I described the remaining work in https://github.com/gokrazy/gokrazy/issues/216#issuecomment-1857444107

**Pull request closed without merging**
