### PR TITLE
cmd/gokr-build-kernel: added missing Raspberry Pi 3 thermal

### PR DESCRIPTION
**Pull request by dtchanpura**
Signed-off-by: Darshil Chanpura <darshil@thatwebsite.xyz>

Enables the temperature for Raspberry Pi 3, following are hwmon related metrics from Node Exporter.

Before:
```
# HELP node_hwmon_chip_names Annotation metric for human-readable chip names
# TYPE node_hwmon_chip_names gauge
node_hwmon_chip_names{chip="soc:firmware_raspberrypi_hwmon",chip_name="rpi_volt"} 1
# HELP node_hwmon_in_lcrit_alarm_volts Hardware monitor for voltage (lcrit_alarm)
# TYPE node_hwmon_in_lcrit_alarm_volts gauge
node_hwmon_in_lcrit_alarm_volts{chip="soc:firmware_raspberrypi_hwmon",sensor="in0"} 0.001
```

After:
```
# HELP node_hwmon_chip_names Annotation metric for human-readable chip names
# TYPE node_hwmon_chip_names gauge
node_hwmon_chip_names{chip="soc:firmware_raspberrypi_hwmon",chip_name="rpi_volt"} 1
node_hwmon_chip_names{chip="thermal_thermal_zone0",chip_name="cpu_thermal"} 1
# HELP node_hwmon_in_lcrit_alarm_volts Hardware monitor for voltage (lcrit_alarm)
# TYPE node_hwmon_in_lcrit_alarm_volts gauge
node_hwmon_in_lcrit_alarm_volts{chip="soc:firmware_raspberrypi_hwmon",sensor="in0"} 0.001
# HELP node_hwmon_temp_celsius Hardware monitor for temperature (input)
# TYPE node_hwmon_temp_celsius gauge
node_hwmon_temp_celsius{chip="thermal_thermal_zone0",sensor="temp0"} 51.54
node_hwmon_temp_celsius{chip="thermal_thermal_zone0",sensor="temp1"} 51.002
# HELP node_hwmon_temp_crit_celsius Hardware monitor for temperature (crit)
# TYPE node_hwmon_temp_crit_celsius gauge
node_hwmon_temp_crit_celsius{chip="thermal_thermal_zone0",sensor="temp1"} 90
```

### CODE REVIEW

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
Thanks very much!

**Comment by dtchanpura** [comment]
It took me an hour or so to test it,  didn't expect that it will be merged in minutes.. 😄

**Comment by stapelberg** [comment]
Merging the change to the kernel config is only part of updating the kernel (and has no immediate effect).

The other part is rebuilding the kernel, and then testing it on at least one raspberry pi 3 before pushing it :)

The build is done:
```
CGO_ENABLED=0 gokr-rebuild-kernel  6,84s user 13,09s system 18% cpu 1:47,52 total
```

Will test and push in a minute.

**Comment by stapelberg** [comment]
Can confirm, I’m getting the following thermals on a Raspberry Pi 3 B now:
```
# HELP node_hwmon_chip_names Annotation metric for human-readable chip names
# TYPE node_hwmon_chip_names gauge
node_hwmon_chip_names{chip="soc:firmware_raspberrypi_hwmon",chip_name="rpi_volt"} 1
node_hwmon_chip_names{chip="thermal_thermal_zone0",chip_name="cpu_thermal"} 1
# HELP node_hwmon_in_lcrit_alarm_volts Hardware monitor for voltage (lcrit_alarm)
# TYPE node_hwmon_in_lcrit_alarm_volts gauge
node_hwmon_in_lcrit_alarm_volts{chip="soc:firmware_raspberrypi_hwmon",sensor="in0"} 0
# HELP node_hwmon_temp_celsius Hardware monitor for temperature (input)
# TYPE node_hwmon_temp_celsius gauge
node_hwmon_temp_celsius{chip="thermal_thermal_zone0",sensor="temp0"} 44.546
node_hwmon_temp_celsius{chip="thermal_thermal_zone0",sensor="temp1"} 45.084
# HELP node_hwmon_temp_crit_celsius Hardware monitor for temperature (crit)
# TYPE node_hwmon_temp_crit_celsius gauge
node_hwmon_temp_crit_celsius{chip="thermal_thermal_zone0",sensor="temp1"} 90
```

**Comment by dtchanpura** [comment]
Also to note, previously `node_scrape_collector_success` for `collector="thermal_zone"` was 0 and after this update it is actually 1.
```
node_scrape_collector_success{collector="thermal_zone"} 1
```

**Comment by stapelberg** [comment]
Nice :) The new kernel version is now committed, so you should be able to pick it up using `go get -u github.com/gokrazy/kernel`.

**Pull request merged**
