### PR TITLE
Add (inofficial) support for CM3 (Compute Module 3)

### PR DESCRIPTION
**Pull request by janisstreib**
The compute module 3 (cm3) uses the same chip as the RPi 3 Model B. The only missing thing required to run gokrazy on cm3 is the required dtb.
This PR adds this file to the gokrazy kernel files.

### CODE REVIEW

**Comment by stapelberg** [comment]
Can you run gokr-rebuild-kernel and include the dtb in this pull request please?

**Comment by stapelberg** [comment]
I was looking at whether a patch similar to https://github.com/gokrazy/kernel/blob/master/0101-expose-UART0-ttyAMA0-on-GPIO-14-15-disable-UART1-tty.patch would be required for the compute module.

But it looks like `arch/arm/boot/dts/bcm2837-rpi-cm3-io3.dts` already maps the serial console to GPIO pin 14/15.

Can you confirm that you have serial input/output working with this dtb on your compute module? For serial input, you’ll need to include `github.com/gokrazy/serial-busybox` in your packer command line, or have a statically linked shell as `/perm/sh` on your permanent partition.

**Comment by janisstreib** [comment]
A special patch is not required. I successfully debugged the CM3 with GPIO 14/15 without any further patches.

**Comment by stapelberg** [comment]
Great, thank you!

**Pull request merged**
